### ISSUE TITLE
invalid syntax in file msaa.py

### ISSUE THREAD

**Issue by thu2004** [phuslu/pyMSAA#1]
D:\home\projects\pyMSAA>python test_calc.py
Traceback (most recent call last):
  File "test_calc.py", line 5, in <module>
    import msaa
  File "D:\home\projects\pyMSAA\msaa.py", line 260
    yield yield Element(self.IAccessible, objAccChild.value)
              ^
SyntaxError: invalid syntax

**Comment by Forkest** [comment]
fixed in 57ce1c59a644198cab315f68113a553c9133a530
